[package]
name = "fzy-tmux"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[dependencies]
anyhow = "1.0"
libc = "0.2"
tempfile = "3.14"
